name: ReviewSky Sentiment
on:
  workflow_dispatch:  # Triggered by cron-job.org

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Run analysis
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          chmod +x sentiment.sh
          ./sentiment.sh
      - name: Commit results
        run: |
          git config user.name "GH Actions"
          git config user.email "actions@github.com"
          git add data/sentiment.json
          git commit -m "Update $(date)" && git push || echo "No changes"
